'use client'
import Header from '@/components/header'
import './globals.css'
import { SessionProvider } from 'next-auth/react'
 
export const metadata = {
  title: 'Lista Tarefas',
  description: 'Generated by create next app',
}
 
interface IProps{
  children: React.ReactNode
}
 
export default function RootLayout({children}: IProps) {
  return (
    <html lang="pt-br">
      <body>
        <SessionProvider>
          <Header/>
          {children}
        </SessionProvider>
      </body>
    </html>
  )
}